### ISSUE TITLE
Rails 2.3.3

### ISSUE THREAD

**Issue by alkesh** [mneumann/postgres-pr#1]
postgres-pr doesn't seem to work with rails 2.3.3.
It raises the error: "undefined method `quote_ident' for PGconn:Class".
Probably due to this commit in rails:
http://github.com/rails/rails/commit/60601234708b34c81dcd6a58a0cad79a7520ce10
